
dictionary = {

    "5:30 AM": "termux-toast LOL",
    "6:0 AM": "termux-toast LOL",
    "6:30 AM": "termux-toast LOL",
    "7:0 AM": "termux-toast LOL",
    "7:30 AM": "termux-toast LOL",
    "8:0 AM": "termux-toast LOL",
    "8:30 AM": "termux-toast LOL",
    "9:0 AM": "termux-toast LOL",
    "9:30 AM": "termux-toast LOL",
    "10:0 AM": "termux-toast LOL",
    "10:30 AM": "termux-toast LOL",
    "11:0 AM": "termux-toast LOL",
    "11:30 AM": "termux-toast LOL",
    "12:0 PM": "termux-toast LOL",
    "12:30 PM": "termux-toast LOL",
    "1:0 PM": "termux-toast LOL",
    "1:30 PM": "termux-toast LOL",
    "2:0 PM": "termux-toast LOL",
    "2:30 PM": "termux-toast LOL",
    "3:0 PM": "termux-toast LOL",
    "3:30 PM": "termux-toast LOL",
    "4:0 PM": "termux-toast LOL",
    "4:30 PM": "termux-toast LOL",
    "5:0 PM": "termux-toast LOL",
    "5:30 PM": "termux-toast LOL",
    "6:0 PM": "termux-toast LOL",
    "6:30 PM": "termux-toast LOL",
    "7:0 PM": "termux-toast LOL",
    "7:30 PM":  "termux-toast LOL",
    "8:0 PM": "termux-toast LOL",
    "8:30 PM": "termux-toast LOL",
    "9:0 PM": "termux-toast LOL",
    "9:30 PM": "termux-toast LOL",
    "10:0 PM": "termux-toast LOL",
    "10:30 PM": "termux-toast LOL",
    "11:0 PM": "termux-toast LOL",
    "11:30 PM": "termux-toast LOL",

}
